// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdCt6GaCpe_8u7IZTHp1f4mDfmcE-s1Nk',
    appId: '1:127168039878:web:fcb31541e656b2517b80c7',
    messagingSenderId: '127168039878',
    projectId: 'my-ai-chat-248',
    authDomain: 'my-ai-chat-248.firebaseapp.com',
    storageBucket: 'my-ai-chat-248.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0I-IV0-iXU8Sm4rZsdHsoBwx6PJ70zXE',
    appId: '1:127168039878:android:4c3df59583b176937b80c7',
    messagingSenderId: '127168039878',
    projectId: 'my-ai-chat-248',
    storageBucket: 'my-ai-chat-248.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLTVSn64kkBqC8J0KDGKovzwO9HPKLlvc',
    appId: '1:127168039878:ios:2efe58dd947f24847b80c7',
    messagingSenderId: '127168039878',
    projectId: 'my-ai-chat-248',
    storageBucket: 'my-ai-chat-248.firebasestorage.app',
    iosBundleId: 'com.example.personalAiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLTVSn64kkBqC8J0KDGKovzwO9HPKLlvc',
    appId: '1:127168039878:ios:2efe58dd947f24847b80c7',
    messagingSenderId: '127168039878',
    projectId: 'my-ai-chat-248',
    storageBucket: 'my-ai-chat-248.firebasestorage.app',
    iosBundleId: 'com.example.personalAiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdCt6GaCpe_8u7IZTHp1f4mDfmcE-s1Nk',
    appId: '1:127168039878:web:e376e860df06254c7b80c7',
    messagingSenderId: '127168039878',
    projectId: 'my-ai-chat-248',
    authDomain: 'my-ai-chat-248.firebaseapp.com',
    storageBucket: 'my-ai-chat-248.firebasestorage.app',
  );
}
